### ISSUE TITLE
`select_n_pcs_countsplit` casts `train_data` and `test_data` inputs to `int`

### ISSUE THREAD

**Issue by sfohr** [bio-datascience/BacSC#1]
`select_n_pcs_countsplit` is used to select the number of principal components based on arguments `train_data` and `test_data`, that result from the countsplitting procedure, both variance stabilized and scaled. In `select_n_pcs_countsplit` - `ut.convert_to_dense_counts` is called on both the train and test data, which extracts the specified layers but then casts the arrays to type `int`.

A potential solution might be to introduce a new function `ut.convert_to_dense` that can be used in `select_n_pcs_countsplit` and alter `ut.convert_to_dense_counts`:

```python
def convert_to_dense_counts(adata, layer=None):

    dense_data = convert_to_dense(adata, layer)
    count_data = dense_data.astype(int)

    return count_data
```

**Comment by johannesostner** [comment]
Fixed in latest commit.
In the datasets I checked so far, this had no influence on the selection of `k_opt`, but there might be implications for other datasets
